### ISSUE TITLE
[BUG] LoginError

### ISSUE THREAD

**Issue by Lxk-Kallen** [rawandahmad698/PyChatGPT#113]
Code
```
from pychatgpt import Chat
from typing import Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()
chat = Chat(email="email", password="password") 

@app.get("/ask")
async def get(ask): 
    answer, parent_conversation_id, conversation_id = chat.ask(ask);
    print('ask:' + ask + 'answer:' + answer);
    return answer;

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

ErrorLog
```
[OpenAI] Email address: email
[OpenAI] Password: password
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test\main.py", line 7, in <module>
    chat = Chat(email="anatool118@outlook.com", password="Zhou1994")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pychatgpt\main.py", line 56, in __init__
    self._setup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pychatgpt\main.py", line 145, in _setup
    self._create_access_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pychatgpt\main.py", line 163, in _create_access_token
    openai_auth.create_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pychatgpt\classes\openai.py", line 133, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!
```

**Comment by Lxk-Kallen** [comment]
![image](https://user-images.githubusercontent.com/72729568/206955788-d258d84f-ad5b-4c34-a55e-993de6c0fb92.png)
Under the same environment, the website can be used normally

**Comment by Lxk-Kallen** [comment]
![image](https://user-images.githubusercontent.com/72729568/206955939-a981fa6c-d522-41d2-aa21-b7ece4125697.png)Under the same environment, the website can be used normally

**Comment by Dooder07** [comment]
Your login is visible. @Lxk-Kallen 
Also I can confirm. lol

**Comment by acheong08** [comment]
Tracking here https://github.com/acheong08/ChatGPT/issues/261

**Comment by AshCript** [comment]
I've got the same problem ! x( x( x( 😭
![ChatGPTError](https://user-images.githubusercontent.com/33932294/208147664-0e17b8f7-3e98-4cf7-9463-6c05a776519d.png)

**Comment by HaleTime** [comment]
Same issue here .. Is there a solution here?

**Comment by harshvardhan96** [comment]
I'm getting the same issue, any solution for it yet ?

**Comment by frankShih** [comment]
Currently, I can only login through Google & M$ account. So that I am not able to get account & password.
Any suggestions?
