### ISSUE TITLE
"IndexError: list index out of range" in auth.py at line 357

### ISSUE THREAD

**Issue by LEGion-42** [rawandahmad698/PyChatGPT#12]
Here's the full error message

```
Traceback (most recent call last):
  File "*\PyChatGPT-master\main.py", line 45, in <module>
    open_ai_auth.begin()

  File "*\PyChatGPT-master\Classes\auth.py", line 127, in begin
    self.part_two()

  File "*\PyChatGPT-master\Classes\auth.py", line 155, in part_two
    self.part_three(token=csrf_token)

  File "*\PyChatGPT-master\Classes\auth.py", line 185, in part_three
    self.part_four(url=url)

  File "*\PyChatGPT-master\Classes\auth.py", line 215, in part_four
    self.part_five(state=state)

  File "*\PyChatGPT-master\Classes\auth.py", line 265, in part_five
    self.part_six(state=state, captcha=None)

  File "*\PyChatGPT-master\Classes\auth.py", line 298, in part_six
    self.part_seven(state=state)

  File "*\PyChatGPT-master\Classes\auth.py", line 333, in part_seven
    self.part_eight(old_state=state, new_state=new_state)

  File "*\PyChatGPT-master\Classes\auth.py", line 357, in part_eight
    access_token = re.findall(r"accessToken\":\"(.*)\"", next_data.text)[0]
IndexError: list index out of range
```

**Comment by rawandahmad698** [comment]
Read: https://github.com/rawandahmad698/PyChatGPT/issues/5
