### ISSUE TITLE
[BUG] Please update bypass first step and other.

### ISSUE THREAD

**Issue by und3fined** [rawandahmad698/PyChatGPT#125]
**Describe the bug**
Can't open https://chat.openai.com/auth/login

**To Reproduce**
First login error

**Expected behavior**
Login success

**Screenshots**
```
>> Tracking conversation enabled.
>> Access Token missing or expired. Attempting to create them...
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
[OpenAI][1] StatusCode = 403
Traceback (most recent call last):
  File "chat-gpt/main.py", line 17, in <module>
    chat = Chat(email="me@und3fy.dev", password="th*SKq&Vg&2BKdkq55gU", options=options)
  File "chat-gpt/.env/lib/python3.10/site-packages/pychatgpt/main.py", line 56, in __init__
    self._setup()
  File "chat-gpt/.env/lib/python3.10/site-packages/pychatgpt/main.py", line 145, in _setup
    self._create_access_token()
  File "chat-gpt/.env/lib/python3.10/site-packages/pychatgpt/main.py", line 163, in _create_access_token
    openai_auth.create_token()
  File "chat-gpt/.env/lib/python3.10/site-packages/pychatgpt/classes/openai.py", line 134, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!
```

**Version Info (please complete the following information):**
Latest

**Additional context**
 "Host": "ask.openai.com" maybe won't work

**Comment by artificial-cassiano** [comment]
Same issue..

**Comment by drtk712** [comment]
same...

**Comment by GaoQ1** [comment]
so what's the problem?

**Comment by zenorochaV1** [comment]
same

**Comment by rawandahmad698** [comment]
An Update is coming, check out our Discord server in readmeZ

**Comment by SupritYoung** [comment]
same

**Comment by zenorochaV1** [comment]
new update



| |
zenorocha
|
|
***@***.***
|




---- Replied Message ----
| From | Rawand Ahmed ***@***.***> |
| Date | 12/17/2022 03:30 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [rawandahmad698/PyChatGPT] [BUG] Please update bypass first step and other. (Issue #125) |

An Update is coming, check out our Discord server in readmeZ

**Comment by aetherwu** [comment]
Good to wait for a new release.
