### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by abdibrokhim** [rawandahmad698/PyChatGPT#142]
Traceback (most recent call last):
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/main.py", line 24, in <module>
    chat = Chat(email="alimov.dayi@gmail.com", password="ali494949", options=options)
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/pychatgpt/main.py", line 56, in __init__
    self._setup()
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/pychatgpt/main.py", line 145, in _setup
    self._create_access_token()
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/pychatgpt/main.py", line 163, in _create_access_token
    openai_auth.create_token()
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/pychatgpt/classes/openai.py", line 128, in create_token
    response = self.__session.get(url=url, headers=headers)
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/tls_client/sessions.py", line 363, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/Users/abdibrokhim/VisualStudioCode/OpenDataHackathon/Lychee/backend/venv/lib/python3.10/site-packages/tls_client/sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://chat.openai.com/auth/login": dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by ECTO-1A** [comment]
Just a heads up, you put you email and password in clear text

**Comment by abdibrokhim** [comment]
what do you mean? it is

**Comment by acheong08** [comment]
> [Discord Discussion](https://discord.gg/MqeaZsy4F5) Current State: Not maintained. Not Working.

**Comment by raskalc** [comment]
BRO, WHY U SENDING YOUR F*CKING PASSWORD IN LOGS?
WHYYYYYYYYYYY?

**Comment by abdibrokhim** [comment]
Oh shitttt, bro thank you
