### ISSUE TITLE
[BUG] Cannot login

### ISSUE THREAD

**Issue by tiagorangel2011** [rawandahmad698/PyChatGPT#143]
**Describe the bug**
I can't log in. Error:
```
Traceback (most recent call last):
  File "c:\Users\HUAWEI\OneDrive\Ambiente de Trabalho\Trabalhos\Python 2\Hey Clippy\chatgpt.py", line 3, in <module>
    chat = Chat(email="<my email>", password="<my password>")
  File "C:\Users\XXXXXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_XXXXXXXX\LocalCache\local-packages\Python39\site-packages\pychatgpt\main.py", line 56, in __init__
    self._setup()
  File "C:\Users\XXXXXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_XXXXXXXX\LocalCache\local-packages\Python39\site-packages\pychatgpt\main.py", line 145, in _setup
    self._create_access_token()
  File "C:\Users\XXXXXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_XXXXXXXX\LocalCache\local-packages\Python39\site-packages\pychatgpt\main.py", line 163, in _create_access_token
    openai_auth.create_token()
  File "C:\Users\XXXXXXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_XXXXXXXX\LocalCache\local-packages\Python39\site-packages\pychatgpt\classes\openai.py", line 133, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!
```

**To Reproduce**
1. Run any kind of demo
2. Get the error

**Expected behavior**
Simply run without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/70700766/227735744-75c02997-9fe7-4c8e-aeec-7f8012b98526.png)

**Version Info (please complete the following information):**
- Chatgptpy version: Latest version as of 25/3/2023
- Dependency version: Everything latest version as of 25/3/2023

**Additional context**
Before you ask me, yes, the password and email ARE correct. Double-checked.

**Comment by egorbabushka** [comment]
I also get this error. I displayed the error code that the site gives out and it gave out "403 Forbidden".

**Comment by tiagorangel2011** [comment]
Maybe related to #71?
