### ISSUE TITLE
[BUG] "Failed to make the first request, Try that again!" get access-token failed 

### ISSUE THREAD

**Issue by liuyan345** [rawandahmad698/PyChatGPT#147]
[OpenAI] Email address: ssssssss@gmail.com
[OpenAI] Password: ssssssss
[OpenAI] Beginning auth process
[OpenAI][1] Making request to https://chat.openai.com/auth/login
Traceback (most recent call last):
  File "/data/www/test/main.py", line 11, in <module>
    chat = Chat(email="ssssssss@gmail.com", password="sssssss")
  File "/usr/local/python3/lib/python3.9/site-packages/pychatgpt/main.py", line 56, in __init__
    self._setup()
  File "/usr/local/python3/lib/python3.9/site-packages/pychatgpt/main.py", line 145, in _setup
    self._create_access_token()
  File "/usr/local/python3/lib/python3.9/site-packages/pychatgpt/main.py", line 163, in _create_access_token
    openai_auth.create_token()
  File "/usr/local/python3/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 133, in create_token
    raise Exceptions.Auth0Exception("Failed to make the first request, Try that again!")
pychatgpt.classes.exceptions.Auth0Exception: Failed to make the first request, Try that again!

**Comment by Zeffut** [comment]
i got the same

**Comment by gpx-4** [comment]
got the same issue
