### ISSUE TITLE
ModuleNotFoundError: No module named 'tls_client'

### ISSUE THREAD

**Issue by Konard** [rawandahmad698/PyChatGPT#88]
```
from pychatgpt import Chat

chat = Chat(email="email", password="password")
chat.cli_chat()
```
code is placed in `src` folder in `run.py` file.

When I run it, it get:

```
gitpod /workspace/PyChatGPT/src (master) $ python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from pychatgpt import Chat
  File "/workspace/PyChatGPT/src/pychatgpt/__init__.py", line 1, in <module>
    from .main import Chat
  File "/workspace/PyChatGPT/src/pychatgpt/main.py", line 11, in <module>
    from .classes import openai as OpenAI
  File "/workspace/PyChatGPT/src/pychatgpt/classes/openai.py", line 12, in <module>
    import tls_client
ModuleNotFoundError: No module named 'tls_client'
```

**Comment by rawandahmad698** [comment]
run "pip3 install -r requirements"
