### ISSUE TITLE
Unable to run Error.

### ISSUE THREAD

**Issue by bbhxwl** [rawandahmad698/PyChatGPT#90]
from pychatgpt import Chat

chat = Chat(email="iw********", password="*****", options=options)
answer = chat.ask("How are you?")
print(answer)

```
D:\pythonProject\test\venv\Scripts\python.exe D:\pythonProject\test\main.py 
Traceback (most recent call last):
  File "D:\pythonProject\test\main.py", line 1, in <module>
    from pychatgpt import Chat
  File "D:\pythonProject\test\venv\lib\site-packages\pychatgpt\__init__.py", line 1, in <module>
    from .main import Chat
  File "D:\pythonProject\test\venv\lib\site-packages\pychatgpt\main.py", line 10, in <module>
    from .classes import openai as OpenAI
  File "D:\pythonProject\test\venv\lib\site-packages\pychatgpt\classes\openai.py", line 18, in <module>
    from svglib.svglib import svg2rlg
  File "D:\pythonProject\test\venv\lib\site-packages\svglib\svglib.py", line 29, in <module>
    from reportlab.pdfbase.pdfmetrics import stringWidth
  File "D:\pythonProject\test\venv\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 22, in <module>
    from reportlab.pdfbase import _fontdata
  File "D:\pythonProject\test\venv\lib\site-packages\reportlab\pdfbase\_fontdata.py", line 101, in <module>
    from reportlab.rl_config import T1SearchPath
  File "D:\pythonProject\test\venv\lib\site-packages\reportlab\rl_config.py", line 45, in <module>
    _DEFAULTS=_defaults_init()
  File "D:\pythonProject\test\venv\lib\site-packages\reportlab\rl_config.py", line 13, in _defaults_init
    from reportlab.lib.utils import rl_exec
  File "D:\pythonProject\test\venv\lib\site-packages\reportlab\lib\utils.py", line 15, in <module>
    from PIL import Image
  File "D:\pythonProject\test\venv\lib\site-packages\PIL\Image.py", line 132, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (D:\pythonProject\test\venv\lib\site-packages\PIL\__init__.py)

Process finished with exit code 1

```

**Comment by rawandahmad698** [comment]
Update PIL
