### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by feter** [rawandahmad698/PyChatGPT#93]
[OpenAI][5] Captcha saved to captcha.png in the current directory
[OpenAI][5] Please solve the captcha and press enter to continue: 45fgab
[OpenAI][5] Continuing...
[OpenAI][6] Making request to https://auth0.openai.com/u/login/identifier
Traceback (most recent call last):
  File "/www/project/chatGPT/test3.py", line 11, in <module>
    chat = Chat(email="517XXXX@XXX.com", password="XXXXX")
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/main.py", line 47, in __init__
    self._setup()
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/main.py", line 130, in _setup
    self._create_access_token()
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/main.py", line 148, in _create_access_token
    openai_auth.create_token()
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 131, in create_token
    self._part_two()
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 157, in _part_two
    self._part_three(token=csrf_token)
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 190, in _part_three
    self._part_four(url=url)
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 218, in _part_four
    self._part_five(state=state)
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 260, in _part_five
    self._part_six(state=state, captcha=captcha_input)
  File "/www/project/venv/lib/python3.9/site-packages/pychatgpt/classes/openai.py", line 300, in _part_six
    raise Exceptions.Auth0Exception("[OpenAI][6] Email not found, Check your email address and try again!")
pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][6] Email not found, Check your email address and try again!

**Comment by rawandahmad698** [comment]
it also gives you an error: 
`pychatgpt.classes.exceptions.Auth0Exception: [OpenAI][6] Email not found, Check your email address and try again!`
